### ISSUE TITLE
Huey altitude ranges display incorrectly

### ISSUE THREAD

**Issue by rrutko** [llamaXc/winwing-ufc-addon#2]
In Huey, Altitude reads incorreectly only during certain ranges. 1-60 feet correct, 70-79 feet displays 60-69 feet, 80-89 correct, 90-99 displays 80-89, 100+ correct. 170-179 displays 160-169, 180-189 correct, 190-199 displays 180-189. etc.

**Comment by llamaXc** [comment]
Nice find, I’ll look into this and report back. Must be a formatting issue
when constructing the digits. Thanks

**Comment by llamaXc** [comment]
Fixed in latest [commit](https://github.com/llamaXc/winwing-ufc-addon/commit/3e06eadb5170533cd9aa5ffae485e8c09463935a)
